version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install pytest

  build:
    commands:
      - pytest
      - python app.py

artifacts:
  files:
    - '**/*'
